name: update commands.md

on:
  push:
    branches: 
      - 'main'

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: create the file
        run: |
          npm i
          npm run create-commands.md

      - name: git stuff
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git add commands.md
          git commit -m "update commands.md"
          git push origin main
